<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYCzLnir\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYCzLnir/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYCzLnir.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYCzLnir\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerYCzLnir\App_KernelDevDebugContainer([
    'container.build_hash' => 'YCzLnir',
    'container.build_id' => '4d908818',
    'container.build_time' => 1580572172,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYCzLnir');
